version = 1

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Municipalidad de Buin"
SPDX-FileContributor = "MerakiLabs"
SPDX-License-Identifier = "LicenseRef-Buin-MerakiLabs"
