name = "decretos-firma-api"
main = "src/index.js"
compatibility_date = "2026-08-01"

[[d1_databases]]
binding = "DB"
database_name = "decretos_firma_db"
database_id = "9c078beb-7465-41f5-93c3-3d076306b0ad"
migrations_dir = "migrations"
